networks:
  koi_networks:
    driver: bridge

services:
  mysql:
    image: lcaohoanq/sample-mysql-db:2.0
    container_name: mysql_db_koi_development
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - koi_networks
    environment:
      MYSQL_ROOT_PASSWORD: Luucaohoang1604^^
      MYSQL_DATABASE: mysql_starter
      MYSQL_USER: lcaohoanq
      MYSQL_PASSWORD: Luucaohoang1604^^
    volumes: 
      - mysql_data:/var/lib/mysql        # Persist MySQL data
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin_ui_koi_development
    networks:
      - koi_networks
    environment:
      PMA_HOST: mysql_db_koi_development                 # Hostname of the MySQL service (container name)
      PMA_USER: root                     # MySQL root user
      PMA_PASSWORD: Luucaohoang1604^^    # MySQL root password
    ports:
      - "81:80"                        # Expose phpMyAdmin on port 81

  prometheus:
    image: prom/prometheus
    container_name: prometheus_koi_development
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
    networks:
      - koi_networks
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # connection Prometheus server URL
  # http://prometheus:9090(prometheus is the service name)
  # not use localhost because localhost refer to grafana itself
  grafana:
    image: grafana/grafana
    container_name: grafana_koi_development
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=sysadmin
      - GF_SECURITY_ADMIN_PASSWORD=sysadmin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - koi_networks

volumes:
  mysql_data:
    driver: local
  grafana_data:
    driver: local
