name: CD for Koi-Auction-BE

on:
  push:
    branches: [ "master", "main", "prod", "production" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push (BE + MySQL DB) Docker Image
        run: |
          # Use the new version to tag the Docker image
          docker build -f DockerfileJavaSpringBoot -t ${{ secrets.DOCKER_USERNAME }}/koiauction_on_cd:latest .
          docker build -f Dockerfile-db -t ${{ secrets.DOCKER_USERNAME }}/koiauction_on_ci:latest .
          
          # Push the versioned image with tag to DockerHub
          docker push ${{ secrets.DOCKER_USERNAME }}/koiauction_on_cd:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/koiauction_on_ci:latest

      - name: Log out from DockerHub
        run: docker logout
