name: CD for Koi-Auction-BE

on:
  push:
    branches: [ "master", "main", "prod", "production" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Current Version
        id: get_version
        run: |
          # Read the current version from the VERSION file
          current_version=$(cat VERSION)
          echo "Current version is $current_version"
          
          # Split the version number by "." and increment the last number
          major_version=$(echo $current_version | cut -d. -f1)
          minor_version=$(echo $current_version | cut -d. -f2)
          new_version="$major_version.$((minor_version + 1))"
          
          echo "New version is $new_version"
          
          # Store the new version in a GitHub Actions environment variable
          echo "version=$new_version" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          # Use the new version to tag the Docker image
          docker build -f DockerfileJavaSpringBoot -t ${{ secrets.DOCKER_USERNAME }}/koiauction_on_cd:${{ env.version }} .
          
          # Push the versioned image with tag to DockerHub
          docker push ${{ secrets.DOCKER_USERNAME }}/koiauction_on_cd:${{ env.version }}

      - name: Update VERSION File
        run: |
          # Update the VERSION file with the new version
          echo ${{ env.version }} > VERSION
          
          # Configure Git to commit the change
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit and push the updated VERSION file
          git add VERSION
          git commit -m "Increment version to ${{ env.version }}"
          git push

      - name: Log out from DockerHub
        run: docker logout