name: CI for Koi-Auction-BE

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: lcaohoanq/koiauction_on_ci:1.3  # Use the MySQL version you need
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Luucaohoang1604^^
          MYSQL_DATABASE: koi_company_dev_db #inside contain dataV15.sql
          MYSQL_USER: lcaohoanq
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 -uroot -pLuucaohoang1604^^ --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run All Tests
        run: mvn -B clean test --file pom.xml
        continue-on-error: false
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/koi_company_dev_db
          SPRING_DATASOURCE_USERNAME: lcaohoanq
          SPRING_DATASOURCE_PASSWORD: Luucaohoang1604^^
          SPRING_PROFILES_ACTIVE: dev  # Set the active profile to 'dev'

      - name: Generate Surefire Report
        if: always()
        run: mvn surefire-report:report-only

      - name: Set up Python
        if: always()
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pandas and Openpyxl
        if: always()
        run: |
          pip install pandas
          pip install openpyxl

      - name: Convert XML to Excel
        if: always()
        run: python convert_xml_to_excel.py

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/site/surefire-report.html
            target/surefire-reports/test-report.xlsx